version: '3.8'

services:
  web:
    image: mightysanjay/my-passive
    ports:
      - "5000:5000"
    stdin_open: true  # Equivalent to -i
    tty: true         # Equivalent to -t
    command: ["sh", "-c", "./start.sh && tail -f /dev/null"]
