version: '3.8'

services:
  web:
    image: mightysanjay/my-passive:v1
    ports:
      - "5000:5000"
    stdin_open: true 
    tty: true         
    command: ["sh", "-c", "./start.sh && tail -f /dev/null"]
