services:
  web:
    image: mightysanjay/my-passive:v3   
    build: .
    ports:
      - "5000:5000"
    stdin_open: true  
    tty: true         
    command: ["sh", "-c", "./start.sh && tail -f /dev/null"]
