version: '3.8'
services:
  web:
    image: CICD-PassiveLiveliness:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    volumes:
      - .:/app